spring.application.name=turnos
server.port=9091

# Base de datos H2 en memoria (built-in)
spring.datasource.url=jdbc:h2:mem:db_turnos;
# MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 (opcional)
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Configuración de JPA
spring.jpa.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=warn
logging.level.org.springframework.hibernate=error
logging.level.org.springframework.web.servlet.DispatchServlet=debug
logging.pattern.console='%clr(%d{yyyy-MM-dd HH:mm:ss}){magenta} %clr(%-5p){blue} %clr(%c{1}){blue}:%clr(%L){cyan} - %m%n'
